### ISSUE TITLE
bug with PL2 using existing clusters

### ISSUE THREAD

**Issue by k-mazurek** [arouseKUMC/WaveLimit#5]
In the main WaveLimit file, there's a bug if trying to use existing clusters from a PL2/PLX file. (line 228)

I've added the following code which I think works

`(line 228) if options.use_existing_clusters`
`  if plx_file_flag`
`  unique_cluster_indexes = find(tscounts(:,1+ch)>0)-1;    % make 0 unsorted (rather than 1)`
`  else`
`  unique_cluster_indexes = nex_file_unit_numbers(ch_indexes);`
`  end`

Before only the `unique_cluster_indexes = nex_file_unit_numbers(ch_indexes);` was used

I ran into this because when using the autocluster, one of the channels which was noisy came up with 39+ clusters, this caused a problem because then for some reason it labeled the sig### which a character that's outside of a-z. Plus I don't think OFS v3 liked having 39 clusters so it actually removed all the channels (or something like that).

**Comment by arouseKUMC** [comment]
Hi Kevin,

Just so I’m clear, this is two separate issues correct?  One found because the other didn’t work.  You’re using the use_existing_clusters flag with a file pre-sorted in plexon not my unit identifier.  If so, your fix looks good to me.

Then, with my autocluster part of the code, we can at least add a maximum number of cluster centers to prevent this although might be worth figuring out what’s going on.  Can you share with me the datafile with the issue through Box?

-Adam

**Comment by k-mazurek** [comment]
Hey Adam,

Yes you're correct (2 bugs). I initially tried using your autocluster, but one of my channels ended up with over 30 centers. I think the stim artifacts are causing an issue, but where this became a problem was when trying to view the nex file in OFS, specifically the file tried to name the sigXXXa-z but after z came characters that it couldn't render.

My fix was to revert to using my predefined centers which is why I used the code above. I'll share the file over box shortly.
